package io.ioconic.challenge.service_layer

import io.ioconic.challenge.data_layer.model.Score
import io.ioconic.challenge.data_layer.model.isScoreFromThisMonth
import io.ioconic.challenge.data_layer.repository.mongo.ScoreMongoRepository
import io.ioconic.challenge.data_layer.repository.redis.ScoreRedisRepository
import java.time.LocalDateTime
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Service

@Service
class CreateScoreService(
        private val scoreMongoRepository: ScoreMongoRepository
) {

    @Autowired private lateinit var syncLeaderboardsService: SyncLeaderboardsService

    fun execute(score: Score): Score {
        score.createdAt = score.createdAt ?: LocalDateTime.now()
        // This assignation is for being able to return the score with the id,
        // since the id is generated by the database and is reset to null when
        // saving to redis
        val scoreToReturn = scoreMongoRepository.save(score)

        syncLeaderboardsService.execute(scoreToReturn)

        return scoreToReturn
    }

}
